Fixes issues #376, #366
In Windows SublimeLinter never can find cpplint.py, because subprocess.Popen(['cpplint.py'....
gives 
WindowsError: [Error 193] %1 is not a valid Win32 application